### ISSUE TITLE
App Getter improvements meta issue

### ISSUE THREAD

**Issue by teleclimber** [teleclimber/Dropserver#49]
Working on app getter in the context of #9. Lots of things fall from this work:

- [x] app getter should record and store sandbox log output for later retirval
- [x] on ds-host, make it possible to see sandbox log output, especially if error
- [ ] #50
- [x] make ds-dev auto-reload routes
- [x] in ds-dev app routes should propagate to all open frontends
- [ ] #51

**Comment by teleclimber** [comment]
Closing this because remaining items are not directly relevant to App Getter.
