### ISSUE TITLE
Meta issue for releasing tutorial in docs

### ISSUE THREAD

**Issue by teleclimber** [teleclimber/Dropserver#72]
I want the tutorials that I am writing to actually work in ds-dev as much as possible. Here are some hangups:

- [x] #71 
- [x] #70 
- [x] #68 ideally, somehow
- [x] #55
- [x] See #67, but maybe make API version default to 0, and don't mention it in docs.
- [x] Check and commit fixes to dropserver_app and lib_support, tag versions, and use these versions throughout.
- [x] Better feedback on migration jobs and results. See #14

**Comment by teleclimber** [comment]
Turns out you can just leave out the API in `dropapp.json`.
